### ISSUE TITLE
No global index generated on html build when building multiple modules

### ISSUE THREAD

**Issue by pwoolvett** [pdoc3/pdoc#218] opened 2020-06-17 22:27 UTC
When building several modules's doc into html, there should be a global `index.html`, encompassing all modules.

### Expected Behavior
* A global "index.html" file created indexing all documented modules, just like when running the server
* links from the generated htmls back to the "parent" index.

  `pdoc --html mod1.py mod2.py` ->
    ```shell
    html
    |-- mod1.html
    |-- mod2.html
    |-- index.html
    ```

 
### Actual Behavior
Every module documented, no global index, no back refs
`pdoc --html mod1.py mod2.py` ->
  ```shell
  html
  |-- mod1.html
  |-- mod2.html
  |-- index.html
  ```

### Steps to Reproduce

1. have (at least) two modules/packages to document
2. run `pdoc3 --html mod1.py mod2.py`
3. look into build folder: no global "index.html" found

### Additional info
- pdoc version: `0.8.1`
- related: https://github.com/pdoc3/pdoc/issues/55
- My project currently has the following structure:
  ```shell
  .
  |-- manage.py
  |-- metrics
  |-- my_package
  |-- tests
  ```
  All my "production" code lives inside `my_package` folder, but for devs I'd like to also publish the rest of the codes documentation (namely, `manage.py`, `metrics`, `tests`) .It would be nice to have all documentation in one place, just like the http server does.

**Comment by kernc** [comment] 2020-06-18 10:28
Duplicate of https://github.com/pdoc3/pdoc/issues/101. Please subscribe to that bug for notifications. Welcome to try to fix it, too! :smile:

**Closed** 2020-06-18 12:49 UTC
Labels: duplicate
