### ISSUE TITLE
Is there an option to include private methods in the documentation?

### ISSUE THREAD

**Issue by AErnoult** [pdoc3/pdoc#178] opened 2020-04-06 17:57 UTC
I used pdoc3 to generate the documentation of a quite complex academic research code. It is amazing: the hyperlink are really useful to navigate trough the code structure.
We are several to write together this software, and this documentation is first of all, used internally to understand the code.
However, the utility is know limited because only public method are available.

Is there an option to include private methods in the documentation?

I tried to find a way in the html.mako but without success..

Thank you for your help and your work

**Comment by kernc** [comment] 2020-04-10 20:37
Duplicate of https://github.com/pdoc3/pdoc/issues/90. PR https://github.com/pdoc3/pdoc/pull/144 should hit next release in a few days.

**Closed by kernc** 2020-04-10 20:37 UTC

**Comment by AErnoult** [comment] 2020-04-14 15:00
Thank you very much for your answer, and it seems effectively that overriding the docstrings with __pdoc__ could be a solution.
However I don't find a way to include all my private methods of all my submodules simply. The solution I found is to modify the `is_public` method in `pdoc/_init__.py` by forcing it to return always True. It works but it is certainly not a good solution. Does someone have  a better solution?

**Comment by kernc** [comment] 2020-04-14 19:58
It's a good solution if you're comfortable working with the API, and you don't mind the fact that `pdoc._is_public()` actually isn't public and is, thus, prone to change on a whim.

An alternative for CLI use would be to construct `__pdoc__` in some of your modules dynamically, on the fly, such as:
```py
__pdoc__ = {}

for cls in (Class1, Class2, ...):
    for name, value in inspect.getmembers(cls):
        if name.startswith('_') or re.match(some_pattern, name) or value in some_list:
            __pdoc__[cls.__name__ + '.' + name] = True
```
A yet third alternative would be to just rename the underscored methods you want to make public.

**Comment by AErnoult** [comment] 2020-04-20 15:32
Thanks a lot. It works perfectly
