### ISSUE TITLE
Multioutput highlighting issue

### ISSUE THREAD

**Issue by MaxHalford** [pdoc3/pdoc#179] opened 2020-04-08 11:52 UTC
### Expected Behavior

Inside a code block, when the output takes multiple lines, I expect pydoc to take into account all the output.

### Actual Behavior

pydoc seems to only consider the first line of the output. Here is a screenshot:

<img width="954" alt="Screenshot 2020-04-08 at 13 49 26" src="https://user-images.githubusercontent.com/8095957/78781117-03944b80-79a0-11ea-8513-18a427626817.png">

### Steps to Reproduce

The following code block should be improperly handled:

```py
>>> from creme import stream
>>> import numpy as np

>>> X = np.array([[1, 2, 3], [11, 12, 13]])
>>> Y = np.array([True, False])

>>> X_y = stream.iter_array(
...     X, Y,
...     feature_names=['x1', 'x2', 'x3']
... )
>>> for x, y in X_y:
...     print(x, y)
{'x1': 1, 'x2': 2, 'x3': 3} True
{'x1': 11, 'x2': 12, 'x3': 13} False
```

### Additional info

- pdoc version: `0.7.5`

**Comment by kernc** [comment] 2020-04-08 13:12
Issue duplicate of https://github.com/pdoc3/pdoc/issues/174, fixed in https://github.com/pdoc3/pdoc/commit/572bdf27d32e1fa22799216221af1e68d5906d78. Try master. Should be released soon.

**Closed by kernc** 2020-04-08 13:12 UTC
