### ISSUE TITLE
Swastikas on Documentation?

### ISSUE THREAD

**Issue by thearchitector** [pdoc3/pdoc#356] opened 2021-08-27 19:30 UTC
Browsing through the documentation, I noticed a fair number of swastikas in the footers. My hope is that their meaning is closer to the original religious meanings rather than its Nazi implications.

If so, and in any case really, that should be clarified to avoid possible and frankly probable offense.

**Comment by kalindkaria** [comment] 2021-08-28 04:21
It's true, such religious symbols shouldn't be used for decoration purposes of a website.

**Comment by okuboshigeo** [comment] 2021-08-28 16:56
See https://github.com/mitmproxy/pdoc#pdoc-vs-pdoc3 :(

**Comment by kernc** [comment] 2021-08-29 01:48
Offense has yet to be avoided. :pray: Issue a duplicate of https://github.com/pdoc3/pdoc/issues/87.

@okuboshigeo A rebuttal has been long in the making. It should arrive in time. Don't be sad. :)

**Closed by kernc** 2021-08-29 01:48 UTC
