### ISSUE TITLE
how to install pdoc3 when pdoc is already installed (and what are their differences)

### ISSUE THREAD

**Issue by abubelinha** [pdoc3/pdoc#376] opened 2021-12-29 11:59 UTC
This is not a pdoc bug, but might be a pdoc3 bug. My brand new [pdoc](https://github.com/mitmproxy/pdoc) installation [was running OK](https://github.com/mitmproxy/pdoc/issues/324). 
With pdoc I mean https://github.com/mitmproxy/pdoc

Then I just discovered this github fork called [pdoc3](https://github.com/pdoc3), but oddly, it does not link to the original pdoc project. I only found a tiny reference under the installation instructions in [pdoc3.github.io](https://pdoc3.github.io/pdoc/) pages:
* PyPI package pdoc3. Not to be confused with an older package pdoc this package is a fork of. 

As nothing else is said, I just tried to install pdoc3 to understand their differences.

But after installing pdoc3, now I am so confused about how should I call one or the other either from CLI or as a library. 
I would expect that `pdoc` command will still launch [pdoc](https://github.com/mitmproxy/pdoc), whereas `pdoc3` should be used to launch [pdoc3](https://github.com/pdoc3/pdoc). 
But that's not the case: both `pdoc` and `pdoc3` calls are launching pdoc3.
Is there a way to install one package which uses the same name, without affecting the previously installed one?

I also take the opportunity to ask about the differences (pros and cons) between these two packages.
I would expect that pdoc3 has some improvements over pdoc, but I couldn't find info about them on pdoc3 site.
Are they hidden somewhere?

### Expected Behavior
install pdoc3 on a system where I already have [pdoc](https://github.com/mitmproxy/pdoc), so I can keep using both of them

### Actual Behavior
`pip install pdoc3` made my current `pdoc` installation unusable

### Steps to Reproduce
1. `pip install pdoc`
   `Successfully installed pdoc-8.1.0`
2. `c:\python38\scripts\pdoc --version`
```
pdoc: 8.1.0
Python: 3.8.7
Platform: Windows-7-6.1.7601-SP1
```
3. pip install pdoc3
`Successfully installed pdoc3-0.10.0`
4. `c:\python38\scripts\pdoc --version`
  `pdoc.exe 0.10.0`
  `c:\python38\scripts\pdoc3 --version`
  `pdoc.exe 0.10.0`
5. OK. How can I call "the real pdoc" now ??

### Additional info
- pdoc version:
`pdoc.exe 0.10.0`
(if you mean pdoc3)

**Comment by kernc** [comment] 2022-01-25 01:13
Duplicate of https://github.com/pdoc3/pdoc/issues/131.

**Closed by kernc** 2022-01-25 01:13 UTC

**Comment by abubelinha** [comment] 2022-01-30 11:06
Sorry about not having found those duplicates. 
First of them, almost 3 years ago.
Still no possible solution?

I also posted a question above, which still remains unanswered:

> I also take the opportunity to ask about the differences (pros and cons) between these two packages.
> I would expect that pdoc3 has some improvements over pdoc, but I couldn't find info about them on pdoc3 site.
> Are they hidden somewhere?
> 

Thanks in advance
