### ISSUE TITLE
fenced code blocks breaks linking to other identifies below the fenced block

### ISSUE THREAD

**Issue by pkazmier** [pdoc3/pdoc#120] opened 2019-11-02 19:02 UTC
### Expected Behavior

Linking to identifiers via backticks should work throughout the document.

### Actual Behavior

When a fenced block is used, identifiers after the fenced block that should be linked are not.

### Steps to Reproduce

Add a fenced block to a docstring. Identifiers after the block are no longer links.

### Additional info

- pdoc version: 0.7.1

**Comment by kernc** [comment] 2019-11-04 02:48
Related to https://github.com/pdoc3/pdoc/issues/120 if not duplicate.

**Comment by kernc** [comment] 2019-11-05 00:34
A little tight on time myself, I don't suppose you'd care to investigate?

**Comment by kernc** [comment] 2020-01-11 02:12
Duplicate of https://github.com/pdoc3/pdoc/issues/134, fixed in https://github.com/pdoc3/pdoc/commit/d6eca2a22425d3cb5e459ff75c8f79946efb28b7.

**Closed by kernc** 2020-01-11 02:12 UTC
