### ISSUE TITLE
No support for classic Sphinx Style docstring format?

### ISSUE THREAD

**Issue by johann-petrak** [pdoc3/pdoc#273] opened 2020-10-17 10:10 UTC
I have a project that uses "classic" style docstrings, that style/format gets sometimes called "Sphinx style" and sometimes "reST" style:

```
"""
Some text to describe what the function does. 
This can span several lines.

:param param1: description of first parameter.
   can also span several lines if indented.
:param param2: another one
:returns: description of what is returned
"""
```

This will not detect the `:param` sections and format them properly in the generated HTML.

Am I doing this wrong or is this not supported?
In general, is it possible to somehow configure the expected docstring format or is everything supposed to get
auto-detected (so different files or even different parts in a file could have different formats)? 

I am using pdoc version 0.9.1 with Python 3.7

**Comment by kernc** [comment] 2020-10-17 11:00
Duplicate of https://github.com/pdoc3/pdoc/issues/110. Please subscribe to that issue for updates if interested.

There was some preliminary work in https://github.com/pdoc3/pdoc/pull/198, but nothing acceptable so far. Contributions welcome!

**Closed by kernc** 2020-10-17 11:00 UTC
