### ISSUE TITLE
Calls to importlib.import_module require package argument when attempting relative import

### ISSUE THREAD

**Issue by git-n-pissed** [pdoc3/pdoc#167] opened 2020-02-19 17:35 UTC
### Expected Behavior
pdoc3 correctly generates documentation

### Actual Behavior
pdoc3 does not correctly generate documentation

### Steps to Reproduce

1. Write code that attempts a relative import
2. Run pdoc3.  The command I used was `pdoc3 --force --html --output-dir documentation .`
3. Observe following error:

```
Traceback (most recent call last):
  File "c:\program files\python38\lib\site-packages\pdoc\__init__.py", line 186, in import_module
    module = importlib.import_module(module_path)
  File "c:\program files\python38\lib\importlib\__init__.py", line 122, in import_module
    raise TypeError(msg.format(name))
TypeError: the 'package' argument is required to perform a relative import for '.'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Program Files\Python38\Scripts\pdoc3-script.py", line 11, in <module>
    load_entry_point('pdoc3==0.7.4', 'console_scripts', 'pdoc3')()
  File "c:\program files\python38\lib\site-packages\pdoc\cli.py", line 448, in main
    modules = [pdoc.Module(module, docfilter=docfilter)
  File "c:\program files\python38\lib\site-packages\pdoc\cli.py", line 448, in <listcomp>
    modules = [pdoc.Module(module, docfilter=docfilter)
  File "c:\program files\python38\lib\site-packages\pdoc\__init__.py", line 514, in __init__
    module = import_module(module)
  File "c:\program files\python38\lib\site-packages\pdoc\__init__.py", line 188, in import_module
    raise ImportError('Error importing {!r}: {}'.format(module, e))
ImportError: Error importing '.': the 'package' argument is required to perform a relative import for '.'
```

### Additional info
This wasn't a problem with Python 3.7.3 and has only started happening after upgrading to Python 3.8.1.  Looks like line 185 of **pdoc\\_\_init__.py** need to be updated from:

`module = importlib.import_module(module_path)`

to:

```
package = os.path.basename(os.path.abspath(module_path)) if module_path == '.' else None
module = importlib.import_module(module_path, package)
```

- pdoc version: 0.7.4

**Comment by kernc** [comment] 2020-02-20 15:34
I believe with a mere '.' specified on the command line, `if isdir(module)` branch should have been hit:
https://github.com/pdoc3/pdoc/blob/725bc1f257e34c952497f2a8541fae2a21dc3773/pdoc/__init__.py#L166-L176
Resulting in no possible way for `module_path` to still match a period here, rather it should be the full basename of the current directory:
https://github.com/pdoc3/pdoc/blob/725bc1f257e34c952497f2a8541fae2a21dc3773/pdoc/__init__.py#L183-L185
Reading the [new note here](https://docs.python.org/3/library/os.path.html#module-os.path):
> Changed in version 3.8: ..., isdir(), ... now return False instead of raising an exception for paths that contain characters or bytes unrepresentable at the OS level.

I almost feel this might be a regression in Python itself. I don't have 3.8 to test. Can you help in debugging it? What is the value of `locals()` on line 175?

**Comment by git-n-pissed** [comment] 2020-02-20 23:04
I added `print(locals())` at line 175 as requested.  Here is the result:

`{'module': '.', 'abspath': <function abspath at 0x0000028396135790>, 'basename': <function basename at 0x0000028396135280>, 'dirname': <function dirname at 0x0000028396135310>, 'isfile': <function isfile at 0x0000028396126820>, 'isdir': <function isdir at 0x00000283961268B0>, 'path': 'D:\\Git\\Airframes\\KAI\\KUH-1X\\k02', 'module_name': None}`

**Comment by git-n-pissed** [comment] 2020-02-20 23:06
{'module': '.', 'abspath': <function abspath at 0x0000028396135790>, 'basename': <function basename at 0x0000028396135280>, 'dirname': <function dirname at 0x0000028396135310>, 'isfile': <function isfile at 0x0000028396126820>, 'isdir': <function isdir at 0x00000283961268B0>, 'path': 'D:\\Git\\SOME\\DIR', 'module_name': None}

**Comment by git-n-pissed** [comment] 2020-02-20 23:52
I modified the `import_module` function by adding print statements as follows:

```
def import_module(module, *, reload: bool = False) -> ModuleType:
    """
    Return module object matching `module` specification (either a python
    module path or a filesystem path to file/directory).
    """
    @contextmanager
    def _module_path(module):
        from os.path import abspath, basename, dirname, isfile, isdir
        path = '_pdoc_dummy_nonexistent'
        module_name = inspect.getmodulename(module)
        print("module 1 " + module)
        if isdir(module):
            print(1)
            path, module = dirname(abspath(module)), basename(module)
            print("module 2 " + module)
        elif isfile(module) and module_name:
            print(2)
            path, module = dirname(abspath(module)), module_name

        print("module 3 " + module)
        try:
            print(3)
            sys.path.insert(0, path)
            print(4)
            yield module
            print(5)
        finally:
            print(6)
            sys.path.remove(path)
            print(7)
        print("module 4 " + module)
    if isinstance(module, Module):
        print(8)
        module = module.obj
    if isinstance(module, str):
        with _module_path(module) as module_path:
            try:
                # package = os.path.basename(os.path.abspath(module_path)) if module_path == '.' else None
                # module = importlib.import_module(module_path, package)
                module = importlib.import_module(module_path)
            except Exception as e:
                raise ImportError('Error importing {!r}: {}'.format(module, e))

    assert inspect.ismodule(module)
    # If this is pdoc itself, return without reloading. Otherwise later
    # `isinstance(..., pdoc.Doc)` calls won't work correctly.
    if reload and not module.__name__.startswith(__name__):
        module = importlib.reload(module)
    return module
```

The result:

```
module 1 .
1
module 2 .
module 3 .
3
4
6
7
Traceback (most recent call last):
  File "c:\program files\python38\lib\site-packages\pdoc\__init__.py", line 199, in import_module
    module = importlib.import_module(module_path)
  File "c:\program files\python38\lib\importlib\__init__.py", line 122, in import_module
    raise TypeError(msg.format(name))
TypeError: the 'package' argument is required to perform a relative import for '.'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Program Files\Python38\Scripts\pdoc-script.py", line 11, in <module>
    load_entry_point('pdoc3==0.7.4', 'console_scripts', 'pdoc')()
  File "c:\program files\python38\lib\site-packages\pdoc\cli.py", line 448, in main
    modules = [pdoc.Module(module, docfilter=docfilter)
  File "c:\program files\python38\lib\site-packages\pdoc\cli.py", line 448, in <listcomp>
    modules = [pdoc.Module(module, docfilter=docfilter)
  File "c:\program files\python38\lib\site-packages\pdoc\__init__.py", line 527, in __init__
    module = import_module(module)
  File "c:\program files\python38\lib\site-packages\pdoc\__init__.py", line 201, in import_module
    raise ImportError('Error importing {!r}: {}'.format(module, e))
ImportError: Error importing '.': the 'package' argument is required to perform a relative import for '.'
```

**Comment by kernc** [comment] 2020-02-21 00:05
Ah, sorry. Your last elaborate post really cleared things up for me. :sweat_smile:

The issue you're experiencing has been fixed in commit 1709915249cdbdf9d79f08628a1ff08190678adf (in master) and is pending release in a few days.

**Comment by kernc** [comment] 2020-02-21 00:05
Duplicate of https://github.com/pdoc3/pdoc/issues/157.

**Closed by kernc** 2020-02-21 00:05 UTC
Labels: bug

**Comment by git-n-pissed** [comment] 2020-02-21 16:20
Ah, I see why it appeared that this was caused by Python 3.8.1.  It is because when I was using Python 3.7.3 I had pdoc3 0.7.2 installed.  When I updated to Python 3.8.1 the latest version of pdoc3 (0.7.4) was installed which contained the regression.
