### ISSUE TITLE
Is it possible to exclude a module for generating a html site?

### ISSUE THREAD

**Issue by maiaalx** [pdoc3/pdoc#386] opened 2022-02-11 13:27 UTC
Hi together,
i would like to exclude one module (module is not empty) for running pdoc --html 
Is there any command i could use?

Thank you in advance!

**Comment by kernc** [comment] 2022-02-11 14:03
You could [prepend module name with an underscore](https://pdoc3.github.io/pdoc/doc/pdoc/#what-objects-are-documented), thereby designating it private. Alternatively, you could set [`__pdoc__['module.name'] = False`](https://pdoc3.github.io/pdoc/doc/pdoc/#overriding-docstrings-with-__pdoc__) in some higher-level or top-level module to prevent pdoc from documenting that module.

Duplicate of: https://github.com/pdoc3/pdoc/issues/12, https://github.com/pdoc3/pdoc/issues/52, https://github.com/pdoc3/pdoc/issues/293.

**Closed by kernc** 2022-02-11 14:03 UTC
