### ISSUE TITLE
Coudn't get/parse source of '<Module> 'xxxx''>'

### ISSUE THREAD

**Issue by OscarVanL** [pdoc3/pdoc#88] opened 2019-08-02 14:19 UTC
### Expected Behavior

pdoc3 should create the documentation.

### Actual Behavior

The console shows a cryptic error and no documentation is generated:

`pdoc3 --html xxxxxx`

```
c:\users\*****\appdata\local\programs\python\python36-32\lib\site-packages\pdoc\__init__.py:223: UserWarning: Couldn't get/parse source of '<Module 'xxxxxx'>'
  warn("Couldn't get/parse source of '{!r}'".format(doc_obj))
Traceback (most recent call last):
  File "C:\Users\*****\AppData\Local\Programs\Python\Python36-32\Scripts\pdoc3-script.py", line 11, in <module>
    load_entry_point('pdoc3==0.6.3', 'console_scripts', 'pdoc3')()
  File "c:\users\*****\appdata\local\programs\python\python36-32\lib\site-packages\pdoc\cli.py", line 442, in main
    for module in args.modules]
  File "c:\users\*****\appdata\local\programs\python\python36-32\lib\site-packages\pdoc\cli.py", line 442, in <listcomp>
    for module in args.modules]
  File "c:\users\*****\appdata\local\programs\python\python36-32\lib\site-packages\pdoc\__init__.py", line 605, in __init__
    context=self._context)
  File "c:\users\*****\appdata\local\programs\python\python36-32\lib\site-packages\pdoc\__init__.py", line 605, in __init__
    context=self._context)
  File "c:\users\*****\appdata\local\programs\python\python36-32\lib\site-packages\pdoc\__init__.py", line 569, in __init__
    self.doc[name] = Function(name, self, obj)
  File "c:\users\*****\appdata\local\programs\python\python36-32\lib\site-packages\pdoc\__init__.py", line 1020, in __init__
    assert callable(obj)
AssertionError
```
### Steps to Reproduce

I ran `pdoc3 --html xxxxxx` where xxxxx is the module/folder containing various .py files containing classes, then this error popped up.

### Additional info

- pdoc version: 0.6.3

**Comment by kernc** [comment] 2019-08-02 14:32
Duplicate of https://github.com/pdoc3/pdoc/issues/76.

**Comment by kernc** [comment] 2019-08-06 09:06
Can you share a small example of failing code? Maybe it's not an exact duplicate after all ...

**Comment by OscarVanL** [comment] 2019-08-06 09:18
I tried copying my source files into another folder and running `pdoc --html test_folder` each time I added a file, it ended up failing when I added the `__init__.py` file (which AFAIK is required for making modules in Python) to the folder.

The `__init__.py` file is an empty file, I simply made a new .txt file in Windows and renamed it to `__init__.py`

So maybe it doesn't like empty folders?
```

UserWarning: Couldn't get/parse source of '<Module 'test_folder'>'
  warn("Couldn't get/parse source of '{!r}'".format(doc_obj))
```

**Comment by OscarVanL** [comment] 2019-08-06 09:25
However, if I delete the `__init__.py` folder from it still didn't solve the issue.

I tried moving files one-by-one out of my project folder, and when I removed my `examples` folder (a folder where I have one example implementations of my module) from it, pdoc ran successfully.

The source of this example implementation was as follows:

```
# The .. in the below import makes the example go up two parent two directories since it is placed inside the module,
# in a real-world use-case, remove the .. at the beginning since this wouldn't be necessary
from ..AwsMqttComms import AwsMqttComms
import time
import json


@staticmethod
def a_static_function(client, userdata, message):
    print("Received message on subscribed topic: " + message.topic + " saying " + message.payload)


class ObjectOrientedExample:

    def __init__(self):
        self.INSTANCE_VARIABLE = "See!"

    def aMemberFunction(self, client, userdata, message):
        print(message.topic)
        print(message.payload)
        print(message.qos)
        print(message.retain)
        print("Callbacks can access class member functions too: " + self.INSTANCE_VARIABLE)


if __name__ == "__main__":
    comms = AwsMqttComms(endpoint_uri="XXXXXX", client_id="YYYYYYYYYYy")
    comms.publish("test/data", json.dumps({"message": "Hello from Example Code"}))

    # Each subscribed topics spawns a new thread for that topic, so it does not block.
    # A reference to a function to callback to is passed as an argument, without the brackets to execute ().
    comms.subscribe('test/topic', a_static_function)

    example_object = ObjectOrientedExample()
    comms.subscribe('test/topic2', example_object.aMemberFunction)

    # We have to keep our client's main thread open, otherwise, any threads (connections or subscriptions) started
    # by it also stop.
    while True:
        time.sleep(10)

```

**Comment by kernc** [comment] 2019-08-06 09:27
> So maybe it doesn't like empty source files?

These are then two issues. The warning is just a warning (which, true, we might wish to avoid).
https://github.com/pdoc3/pdoc/blob/5d8974c9b0b1a0c73dad001deab8f3036180bb3e/pdoc/__init__.py#L220-L224

**Comment by kernc** [comment] 2019-08-06 09:30
> The source of this example implementation was as follows:

I believe it might be failing on misdefined staticmethod `a_static_function`. What is a staticmethod doing in a global namespace?

I agree pdoc should handle that better (maybe failing in a more verbose way).

**Comment by OscarVanL** [comment] 2019-08-06 09:35
Yeah, fixing that static method definition placement made it work :) My bad!

It would be nicer if pdoc could state which python file was responsible for it not working. I have quite a few python files in this directory, so tracing which was responsible was a little difficult :)

Thanks for the help.

**Comment by stevegore** [comment] 2019-08-13 01:17
I've also encountered this issue. It was caused by a `@cached_property` annotation.

**Closed** 2019-09-26 22:13 UTC
Labels: bug
