### ISSUE TITLE
Line breaks in source code docstrings are ignored in html documentation

### ISSUE THREAD

**Issue by LeonvanKouwen** [pdoc3/pdoc#317] opened 2021-02-27 12:56 UTC
Source code:
![image](https://user-images.githubusercontent.com/6023630/109387698-3e2e0c00-7903-11eb-878a-8c97814e00c6.png)

Documentation:
![image](https://user-images.githubusercontent.com/6023630/109387730-6158bb80-7903-11eb-98d1-2c088ec2d2b6.png)

### Expected Behavior

`pdoc --html package`

The docstrings for function, classes etc should be printed in the documentation respecting line breaks in the source code. 

### Actual Behavior

Line breaks are ignored.

### Additional info

- pdoc version:     0.9.2

**Comment by vardanagarwal** [comment] 2022-02-23 19:25
The issue still exists. pdoc version: 0.10.0

**Comment by kernc** [comment] 2022-02-25 00:59
Duplicate of https://github.com/pdoc3/pdoc/issues/110.

**Closed by kernc** 2022-02-25 00:59 UTC
