### ISSUE TITLE
References stop working after code blocks

### ISSUE THREAD

**Issue by huettenhain** [pdoc3/pdoc#134] opened 2019-12-08 22:57 UTC
### Steps to Reproduce

1. Create a package named `package`
2. Put the following code into the `__init__.py` of `package`:
    ``````
    """
    reference: `package.foo`
    ```
    code block
    ```
    reference: `package.foo`
    """

    class foo:
        """
        too much technology.
        """
        pass
    ``````
3. Generate documentation using `pdoc3 --html package`

### Expected Behavior
The two references to `package.foo` are both displayed as hyperlinks in the documentation of `package`.

### Actual Behavior
Only the reference _before_ the code block is turned into a hyperlink.

### Additional info
- pdoc version: `pdoc3 0.7.2`

**Comment by kernc** [comment] 2019-12-08 23:13
Seems to be a duplicate of, or at least strongly related to, bug https://github.com/pdoc3/pdoc/issues/106.

**Comment by huettenhain** [comment] 2019-12-08 23:26
Ah yes. I only searched for code _blocks_, feel free to close this out. By the way, I just realized that using 4-space indentation to signal a code block is a workaround for this problem; it only happens when triple backtick code fences are used. Feel free to close this as a duplicate, or keep it open - My workaround will very likely be good enough for me.

**Comment by kernc** [comment] 2020-01-11 02:05
At issue is this regex:
https://github.com/pdoc3/pdoc/blob/b2878214f272d3cd541ca436ae587ba8b98624cd/pdoc/html_helpers.py#L371
which applied on:

    reference: `package.foo`
    ```
    code block
    ```
    reference: `package.foo`

results in the following three matches:

    '`test.foo`'
    '`\ncode block\n`'
    '`\nreference: `'

**Closed** 2020-01-11 02:07 UTC
Labels: bug

**Comment by allefeld** [comment] 2020-07-09 06:48
The same problem occurs after backticks have been used within a link text.

Code:

    `Picture` object: A
    [`tikzpicture` environment](https://pgf-tikz.github.io/pgf/pgfmanual.pdf#subsubsection.12.2.1)
    is represented by a `Picture` object.

Result:

![image](https://user-images.githubusercontent.com/1738353/87006045-ed24a880-c1b7-11ea-9ebd-4cfa36c4c481.png)

The `` `Picture` `` before the explicit link is automatically linked to the description of that class, but after the backticks in the text of the explicit link, it just becomes a normal code span. This effect persists until the end of the respective docstring, across paragraph boundaries.

I suspect regular expressions are not sufficient to parse Markdown syntax.

**Comment by kernc** [comment] 2020-07-10 00:07
@allefeld Mind opening a new issue with this?
