### ISSUE TITLE
Syntax Highlighting offline

### ISSUE THREAD

**Issue by besdollma** [pdoc3/pdoc#337] opened 2021-04-29 12:20 UTC
This is not really an issue but more of a consultation (but there are no discussions available for this repo). 

I see that syntax nightlight is done using Highlight.js, and it is done using their online hosting.
However I am hosting the docs in an offline server (on-prem, no internet).  Is there any way to achieve syntax highlight in such conditions? Is there any tutorial?
Thanks,

**Comment by kernc** [comment] 2021-04-30 02:45
From the top of the head, might be as easy as:
```bash
# Fetch CDN resources into the current directory
find html -name '*.html' | xargs grep -oP 'https://cdnjs[^"]*' | wget -i -
# Replace CDN resources with local ones, based in document root (/)
find html -name '*.html' | xargs sed -iE 's,https://cdnjs([^"]*?/)+,/,g'
```

This is a duplicate of https://github.com/pdoc3/pdoc/issues/136 (please subscribe there). Though, with fairly graceful degradation we do (everything is still readable offline) and with easy workarounds available (as above), unless there are better, simple ideas, I'm leaning to wontfix.

**Closed by kernc** 2021-04-30 02:45 UTC
