### ISSUE TITLE
Bug: It seems the `Args` section does not support code blocks very well

### ISSUE THREAD

**Issue by wq2012** [pdoc3/pdoc#11] opened 2019-01-24 16:54 UTC
### Expected Behavior

I was expecting to be able to use code blocks for `Args` section.

For example, this is my docstring:

```
  def predict(self, test_sequence, args):
    """Predict test sequence labels using UISRNN model.

    Args:
      test_sequence: 2-dim numpy array of real numbers, size: N * D
        - the test observation sequence.
        N - length of one test utterance
        D - observation dimension
        For example:
        ```
        test_sequence =
        [[2.2 -1.0 3.0 5.6]   --> 1st entry of utterance 'iccc'
        [0.5 1.8 -3.2 0.4]    --> 2nd entry of utterance 'iccc'
        [-2.2 5.0 1.8 3.7]    --> 3rd entry of utterance 'iccc'
        [-3.8 0.1 1.4 3.3]    --> 4th entry of utterance 'iccc'
        [0.1 2.7 3.5 -1.7]]   --> 5th entry of utterance 'iccc'
        ```
        Here N=5, D=4.
      args: Inference configurations. See arguments.py for details.
```

### Actual Behavior

Here is what has been rendered:
![screenshot from 2019-01-24 11-53-00](https://user-images.githubusercontent.com/3002724/51694386-b4e2d780-1fce-11e9-968d-8e53e862babf.png)

It did not insert new lines for the multiline code block.

### Steps to Reproduce

N/A

### Additional info

- pdoc version:
0.5.1

**Comment by kernc** [comment] 2019-01-25 01:53
Yeah. I remember something about [(` ``` `) fenced code blocks in Python Markdown only working on document root level](https://python-markdown.github.io/extensions/fenced_code_blocks/#syntax) (0th-level indent). Issue: https://github.com/Python-Markdown/markdown/issues/53

Can you try indenting the code one (markdown, i.e. 4-space) extra level. If it doesn't work, it's probably a duplicate of https://github.com/pdoc3/pdoc/issues/10, likely introduced with the fix to https://github.com/pdoc3/pdoc/issues/5. :flushed:

**Comment by wq2012** [comment] 2019-01-25 03:48
I tried to un-indent the code blocks, and it worked, but it went out of the scope of that argument.

Indenting with extra spaces does not work.

**Comment by kernc** [comment] 2019-01-27 13:55
Fenced code blocks remain an issue Python-Markdown/markdown#53

With indented code block (per Markdown syntax, indented extra *4* spaces), your above example should now that #10 is fixed render as expected.

**Closed** 2019-01-27 13:55 UTC
