### ISSUE TITLE
Strange default description for class variables

### ISSUE THREAD

**Issue by tholok97** [pdoc3/pdoc#171] opened 2020-03-04 13:55 UTC
### Actual Behavior

For a class with a class variable stored in a file `example.py`:

```python
class ExampleClass:
    EXAMPLE_CONSTANT = 3
```
`pdoc3 example.py --output-dir public --force` creates the following file `public/example.md`:

```markdown
Module example
==============

Classes
-------

`ExampleClass()`
:   

    ### Class variables

    `EXAMPLE_CONSTANT`
    :   int([x]) -> integer
        int(x, base=10) -> integer
        
        Convert a number or string to an integer, or return 0 if no arguments
        are given.  If x is a number, return x.__int__().  For floating point
        numbers, this truncates towards zero.
        
        If x is not a number or if base is given, then x must be a string,
        bytes, or bytearray instance representing an integer literal in the
        given base.  The literal can be preceded by '+' or '-' and be surrounded
        by whitespace.  The base defaults to 10.  Valid bases are 0 and 2-36.
        Base 0 means to interpret the base from the string as an integer literal.
        >>> int('0b100', base=0)
        4
```

Why is there a long autogenerated description? In my mind the description should be blank. Our documentation looks really messy at the moment because all of our class variables have this huge description attached that is not useful to us.

### Additional info

- pdoc version: 0.7.4

**Comment by kernc** [comment] 2020-03-04 15:22
Duplicate of https://github.com/pdoc3/pdoc/issues/151, fixed in 0.7.5. :+1:

**Closed by kernc** 2020-03-04 15:22 UTC
