### ISSUE TITLE
Docstrings using reST missing formatting.

### ISSUE THREAD

**Issue by nimbusscale** [pdoc3/pdoc#243] opened 2020-08-15 01:01 UTC
I get that there is limited support for reST, but docstrings using that format seem to turn into a jumbled mess in the HTML documentation as the carriage returns are stripped out. Is there a way to just have the docs include the docstring as a preformatted text? I didn't see this option in the docs, so if I missed it then I apologize.

For example, I have this function:

`def clear_evaluations(rule_name: str, region: str = None, session: boto3.Session = boto3.Session()) -> None:
    """Clears the evaluations for a specified config rule.

    :param rule_name: Name of the config rule.
    :param region: Region where the config rule is configured.
    :param session: A boto3 session, can be used to facilitate using a cross-account
    :return: None
    """`

But in the HTML docs it shows up as shown in this screenshot which is hard for a human to read:

![image](https://user-images.githubusercontent.com/9387643/90301944-b21d3100-de57-11ea-9924-6018fbc08fa6.png)

I tried the Google style and that does come out formatted well, but all our docstrings are in reST given that is the default for PyCahrm. I don't care about bolding or any other format of the text, just want the carriage return preserved so it's human-readable. 

 Thanks for any guidance you can provide.

### Additional info

- pdoc version:

`$ pip freeze | grep pdoc
pdoc3==0.8.4
`

**Comment by kernc** [comment] 2020-08-15 01:19
Duplicate of https://github.com/pdoc3/pdoc/issues/110.

ReST support, other than some [explicitly listed directives](https://pdoc3.github.io/pdoc/doc/pdoc/#supported-rest-directives), is non-existent. Text is interpreted as markdown.

-----
Have tried to override default `to_html()` in your [_config.mako_](https://pdoc3.github.io/pdoc/doc/pdoc/#custom-templates) to something more no-op?
https://github.com/pdoc3/pdoc/blob/cd84fb3b0c512a203742cfdfaa26ba6fb0e535aa/pdoc/templates/html.mako#L17-L18
```py
# config.mako:

def to_html(text):
    return text.replace('\n', '<br>')
```

**Closed by kernc** 2020-08-15 01:19 UTC

**Comment by nimbusscale** [comment] 2020-08-15 17:32
I was able to follow the little breadcrumb kernc provided and I wanted to expand it for others that are looking to sort out the same issue.

It appears pdoc allows you to customize how things are rendered via some config files. These are discussed more here: https://pdoc3.github.io/pdoc/doc/pdoc/#custom-templates. 

So what I did is I created a directory in my project that I called `pdoc-templates` and I copied the `html.mako` into that directory. I just got the file here: https://raw.githubusercontent.com/pdoc3/pdoc/master/pdoc/templates/html.mako

I then updated the `to_html` function to reflect what kenc suggested above. After the I ran the following command:

`pdoc --html --force --template-dir pdoc-templates/ my_package`

This caused the rendered template to treat the docstring as preformatted text. This broke all other rendering, which is fine for us, but markdown and such will not be rendered.

Kernc did reference `config.mako`, but linked to `html.mako`. I tried copying the `config.mako` to the `pdoc-templates` dir and added the `to_html` function to my copy of `config.mako`, but that didn't seem to make a difference. So I'm not sure if kernc wrote `config.mako` by mistake or I did something wrong, but I was able to get it working when updating `html.mako`.

**Comment by kernc** [comment] 2020-08-15 17:59
I _did_ mean _config.mako_. I was under the impression function overrides in _config.mako_ are used preferentially, like `glimpse` in the following example from another project:
https://github.com/kernc/backtesting.py/blob/c8f9cc1e2e71aad5fbcb2fa2895ed4226d01c2d8/doc/pdoc_template/config.mako#L15-L20
