### ISSUE TITLE
can't produce doc with flask route

### ISSUE THREAD

**Issue by marc-moreaux** [pdoc3/pdoc#173] opened 2020-03-17 15:00 UTC
Hello,

When I use a flask route as in:
```
'/module/dir/myapp.py'
from flask import current_app as app

@app.route('/a/path', methods=['GET', 'POST'])
def my_function():
    pass
```
pdoc3 does not run anymore.

I have tried to ignore this file with:
```
'module/dir/__init__.py'
__pdoc__ = {'myapp': False,}
```
But it dit not work.
Is there a way I can ignore this 'dir' directory ?
Thanks :)

pdoc version:
pdoc3 0.7.5

**Comment by kernc** [comment] 2020-03-17 20:23
Seems like a duplicate of https://github.com/pdoc3/pdoc/issues/99.

https://github.com/pdoc3/pdoc/issues/99#issuecomment-596721779 contains some guides on a possible, likely reasonable implementation (i.e. usage exactly as you tried it).

**Closed by kernc** 2020-03-17 20:23 UTC
